version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "moov-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-p88ck02ameu"
s3_prefix = "moov-api"
region = "ap-south-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []